services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    environment:
      RUN_ENV: "docker"
      CELERY_BROKER_URL: redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    volumes:
      - .:/app
    command: celery -A pastebin worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0 

  flower:
    build: .
    volumes:
      - .:/app
    command: celery -A pastebin flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: paste_db   
      POSTGRES_USER: paste_user    
      POSTGRES_PASSWORD: 25112511
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data:
  redis_data:


networks:
  default:
    driver: bridge