# Generated by Django 5.1.3 on 2024-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_paste_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Пароль'),
        ),
    ]
